name: Process PPTX Upload

on:
  push:
    paths:
      - '**.pptx'
      - 'generate.py'

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          pip install python-pptx pandas openpyxl

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Run generate.py to create .pptx, .pdf, .xlsx
        run: |
          mkdir -p output
          python generate.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: updated-files
          path: output/*
